### ISSUE TITLE
Auto-generated passwords for postgres cannot contain % as special character

### ISSUE THREAD

**Issue by tolexy** [kobotoolbox/kobo-install#102]
Not sure how serious this is but wanted to flag. 

when running kobo-install run.py -s passwords are autogenerated for postgres, mongo, and redis.

I ran into an issue where my automated backups were saving into an S3 bucket correctly and on schedule, but as 0 bytes. Digging through logs found that when then URI is created for postgres, if there are certain special characters in any of the username/password strings, postgres will complain and not succeed in a dump. 

This happened to me with an autogenerated pw that included a %  char, but I imagine this would happen with @ as well. Obviously one could just change the password manually which is what I ended up doing, but was a short-lived mystery that the backups werent completeing correctly, and only found out because I check those things.

Perhaps a note on which characters not to use for the uname and pwd during the setup process?  or a check during setup would be helpful?

**Comment by noliveleger** [comment]
Hi @tolexy, 
Can you tell me which version of kobo-docker your version pulls? 
I forced kobo-install to generated a password with both characters `%` and `@` and backup run successfully. 
Do you mind to share your logs as well?

**Comment by jnm** [comment]
@noliveleger we might want to use fewer special characters in the random selection just to make our lives easier:
```
john@scrappy:/tmp/kobo-install$ grep 'mongo.*pass' .run.conf 
  "mongo_root_password": "'6.2k9{ro0h9",
  "mongo_user_password": "nDDVNIVTIGR[",
john@scrappy:/tmp/kobo-install$ ./run.py -cb ps
WARNING: Python-dotenv could not parse statement starting at line 10
WARNING: Python-dotenv could not parse statement starting at line 10
WARNING: Python-dotenv could not parse statement starting at line 10
WARNING: Python-dotenv could not parse statement starting at line 10
          Name                        Command                 State       Ports  
---------------------------------------------------------------------------------
yay-kobobe_mongo_1         docker-entrypoint.sh bash  ...   Restarting           
yay-kobobe_postgres_1      docker-entrypoint.sh bash  ...   Up           5432/tcp
yay-kobobe_redis_cache_1   docker-entrypoint.sh bash  ...   Up           6379/tcp
yay-kobobe_redis_main_1    docker-entrypoint.sh bash  ...   Up           6379/tcp
```
(i'll change the password to remove the single quote and post back here about whether or not it fixes the problem)

We could always—I assume—make the auto-generated passwords longer to compensate for the loss of entropy from using a simpler set of characters

**Comment by jnm** [comment]
> (i'll change the password to remove the single quote and post back here about whether or not it fixes the problem)

Yes, it fixes the problem:
```
john@scrappy:/tmp/kobo-install$ grep 'mongo.*pass' .run.conf 
  "mongo_root_password": "nosinglequote6.2k9{ro0h9",
  "mongo_user_password": "nDDVNIVTIGR[",
john@scrappy:/tmp/kobo-install$ ./run.py -cb ps
          Name                        Command               State     Ports  
-----------------------------------------------------------------------------
yay-kobobe_mongo_1         docker-entrypoint.sh bash  ...   Up      27017/tcp
yay-kobobe_postgres_1      docker-entrypoint.sh bash  ...   Up      5432/tcp 
yay-kobobe_redis_cache_1   docker-entrypoint.sh bash  ...   Up      6379/tcp 
yay-kobobe_redis_main_1    docker-entrypoint.sh bash  ...   Up      6379/tcp 
```
