### ISSUE TITLE
Support for input rds (**rds.amazonaws.com)

### ISSUE THREAD

**Issue by awemulya** [kobotoolbox/kobo-install#116]
**In set up.py I didnot find options to set databse url to rds**
 

**Do kobo install supports setting database url  if used rds **

I do not need postgres container in my setup I use RDS in amazon.

**Comment by jnm** [comment]
It's possible, but maybe it's not supported by the kobo-install question-and-answer setup.

RDS should give you a Postgres host, database name, username, and password, just the same as if you were running your own Postgres server, right? We administer one instance that uses RDS, and this is how we connect KoBo to it.

Is the problem that there's no way to disable the Postgres container without also losing the Redis and MongoDB containers? For that instance I mentioned, they're using ElastiCache and DocumentDB, so they don't run any KoBo back-end containers at all.

**Comment by awemulya** [comment]
Thank you for your help. I will install frontend with kobo-install  as frontend server and will use elasticCache and DocumentsDB along with Rds for backend.

**Comment by awemulya** [comment]
IP address (IPv4) of backend server?
[10.22.10.111]: 
Launching environment
Waiting for PostgreSQL database to be up & running...
Creating network "kobofe_kobo-fe-network" with driver "bridge"
CommandError: Retries exceeded; failed to connect
An error has occurred
It breaks if I do not use backend server.
@jnm  do you ave any plan to support this.

**Comment by awemulya** [comment]
sudo docker-compose -f docker-compose.frontend.yml -f docker-compose.frontend.override.yml -p kobofe up -d
form kobo-docker runs the frontend well.
but I modified env files for backend services.
When I have to update the kobotoolbox, I need to do some things manually.
I will fork and try to find a solution for this type of backend.
