### ISSUE TITLE
Trying send instances to kobo.local gives: Error Generic exception: NOTFOUND (404)

### ISSUE THREAD

**Issue by herculan0** [kobotoolbox/kobo-install#121]
**Description**
 

![image](https://user-images.githubusercontent.com/27815937/93931773-9da14380-fcf5-11ea-8449-c0e28312c7a3.png)
 This happens when I try to send an Instance of a form.(A finished one.)

**Steps to Reproduce**

I Have Setup my own local server. Successufuly Edited my /etc/hosts file in an Virtual Android Device Running with GenyMotion. Android 7.0 to acccess the server in my Arch Linux.
![image](https://user-images.githubusercontent.com/27815937/93931856-b873b800-fcf5-11ea-8e09-10d29512f3aa.png)

Arch Linux Installation:
**Expected behavior**

Here is the URL, I also try to change the server configuration URL to http://kc.kobo.local/super_admin/
but no success at all and the same error arises.

Any idea?

Here is the nginx log with the request:
kf.kobo.local | 192.168.0.90 - - [16/Sep/2020:15:45:06 +0000] “HEAD /submission?deviceID=android_id%3A1d00d11587cd98c1 HTTP/1.1” 404 (0 bytes) “-” “org.koboc.collect.android/v1.27.3-3-gaf2b52f90 Dalvik/2.1.0 (Linux; U; Android 7.0; Custom Tablet Build/NBD92Y)”
kf.kobo.local | 192.168.0.90 - - [16/Sep/2020:15:45:06 +0000] “POST /submission?deviceID=android_id%3A1d00d11587cd98c1 HTTP/1.1” 404 (102 bytes) “-” “org.koboc.collect.android/v1.27.3-3-gaf2b52f90 Dalvik/2.1.0 (Linux; U; Android 7.0; Custom Tablet Build/NBD92Y)”
**Desktop**

 - OS:  ArchLinux 
 - Python Version: 3.8.5

 - Docker Version: 19.03.12-ce
 - Docker Compose Version: 1.27.2
 
**Additional context**

[logs.log](https://github.com/kobotoolbox/kobo-install/files/5263747/logs.log)

Can see more here:
https://community.kobotoolbox.org/t/sending-results-working-in-my-own-local-server-gives-me-error-generic-exception-notfoudn/12383/12

Is any other useful info that I can provide to you guys help to solve the problem?

**Comment by noliveleger** [comment]
Hi @herculan0,

As it's said in the issue template when you open an issue, we are a small team and cannot provide some guidance on GH. We really use it to track bugs and AFAIK it's not a `kobo-install` bug. 
I've responded in the community forum. I'm closing this ticket.
