### ISSUE TITLE
No checks if AWS credentials are entered or valid after selecting answering "yes" to "Do you want to use AWS S3 storage?"

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kobo-install#125]
There are currently no checks if the credentials are entered or are valid after deciding to use AWS S3. I would image the that application will fail or have unexpected actions if this is the case. I'm currently unaware of an official way to verify credentials - perhaps an error should at least prompt the user within the web interface to re-enter correct or missing details? @noliveleger 

https://github.com/kobotoolbox/kobo-install/blob/47164572eb966bb52748de04d48e3330d48d354b/helpers/config.py#L644

**Comment by noliveleger** [comment]
@joshuaberetta, the idea of `kobo-install` is to be used right out of the box without any dependencies (at least in Linux, macOS requires one). We may need to use `boto` to test AWS credentials. Users should detect pretty quickly whether their AWS credentials are good or not. (e.g. Imports and Exports won't work)
We can block empty response though.

**Comment by noliveleger** [comment]
@joshuaberetta, do you want to tackle this?

**Comment by joshuaberetta** [comment]
Sure! @noliveleger
