### ISSUE TITLE
Error during Re-Deployment of Forms

### ISSUE THREAD

**Issue by vijay-khanna** [kobotoolbox/kobo-install#144]
We are able to use Kobo in http mode, and the basic landing page is working fine. 

We are not able to re-deploy the form, and are getting this error.

HTTPConnectionPool(host='xyz.abc.org', port=80): Max retries exceeded with url: /api/v1/forms/1 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))

Could anyone kindly help with a solution / workaround.

**Comment by jnm** [comment]
Have you changed any of your host names after deploying forms? If so, you will need to change the deployment data of the old forms to match your new KoBoCAT host name.

Alternatively, try to create a brand new form and then redeploy that form. Do you see the same error?

**Comment by noliveleger** [comment]
Hi @vijay-khanna,
Have a look at this article https://community.kobotoolbox.org/t/how-to-fix-references-of-old-domain-names-after-migration/13324, it may help you.

**Comment by jnm** [comment]
Please re-open if you continue to experience problems.
