### ISSUE TITLE
Stuck at Pulling enketo_express (kobotoolbox/enketo-express-extra-widgets:2.3.10)...

### ISSUE THREAD

**Issue by vijay-khanna** [kobotoolbox/kobo-install#145]
The Install is getting Stuck at "Pulling enketo_express (kobotoolbox/enketo-express-extra-widgets:2.3.10)..."

**Comment by jnm** [comment]
That would most likely indicate a problem with Docker Hub or network connectivity. To test separately from the `run.py` script, you could try `docker pull kobotoolbox/enketo-express-extra-widgets:2.3.10`.
