### ISSUE TITLE
Fresh install don't finish 

### ISSUE THREAD

**Issue by leibarra** [kobotoolbox/kobo-install#148]
**Description**
When i try to fresh install this don't finish and it show the follow message:
_

> ´KoBoToolbox´ has not started yet. This is can be normal with low CPU/RAM computers.
> 
> Wait for another 600 seconds?
>         1) Yes
>         2) No
> [1]: 2
> 
> Sometimes frontend containers can not communicate with backend containers.
> Restarting the frontend containers usually fixes it.
> 
> Do you want to try?
>         1) Yes
>         2) No
> [1]: 2
> 
> KoBoToolbox could not start! Please try `python3 run.py --logs` to see the logs.

_

**Steps to Reproduce**
1.  i configure mycustomdomain.co in DNS and file server hosts.
2.  i execute:
sudo python3 run.py --setup

> ╔═══════════════════════════════════════════════════════════════╗
> ║ Welcome to KoBoInstall!                                       ║
> ║                                                               ║
> ║ You are going to be asked some questions that will            ║
> ║ determine how to build the configuration of `KoBoToolBox`.    ║
> ║                                                               ║
> ║ Some questions already have default values (within brackets). ║
> ║ Just press `enter` to accept the default value or enter `-`   ║
> ║ to remove previously entered value.                           ║
> ║ Otherwise choose between choices or type your answer.         ║
> ╚═══════════════════════════════════════════════════════════════╝
> Where do you want to install?
> [/data/sdb/.apps/e_Leo.Apps/INFO/02_Proyectos/0014_EngineForms/03_construccion/forms-rt/kobo-docker]:
> Please confirm path [/data/sdb/.apps/e_Leo.Apps/INFO/02_Proyectos/0014_EngineForms/03_construccion/forms-rt/kobo-docker]
>         1) Yes
>         2) No
> [1]:
> Do you want to see advanced options?
>         1) Yes
>         2) No
> [2]:
> What kind of installation do you need?
>         1) On your workstation
>         2) On a server
> [2]:
> Public domain name [mycustomdomain.co]:
> KPI sub domain [kf]:
> KoBoCat sub domain [kc]:
> Enketo Express sub domain name [ee]:
> Do you want to use HTTPS?
>         1) Yes
>         2) No
> [2]: 1
> ╔════════════════════════════════════════════════════════════════════╗
> ║ Please note that certificates must be installed on a reverse-proxy ║
> ║ or a load balancer.                                                ║
> ║ KoBoInstall can install one, if needed.                            ║
> ╚════════════════════════════════════════════════════════════════════╝
> Auto-install HTTPS certificates with Let's Encrypt?
>         1) Yes
>         2) No - Use my own reverse-proxy/load-balancer
> [2]: 2
> Internal port used by reverse proxy is 8080.
> SMTP server [smtp.gmail.com]:
> SMTP port [587]:
> SMTP user [formularios.xxxx@gmail.com]:
> SMTP password [XXXXXXX]:
> Use TLS?
>         1) True
>         2) False
> [1]: 1
> From email address [pgrisalesc@mycustomdomain.co]:
> Super user's username [super_admin]:
> Super user's password [xxxxxx]:
> Do you want to activate backups?
>         1) Yes
>         2) No
> [1]:
> Removing network kobomaintenance_kobo-maintenance-network
> WARNING: Network kobomaintenance_kobo-maintenance-network not found.
> Removing network kobofe_kobo-fe-network
> WARNING: Network kobofe_kobo-fe-network not found.
> Network kobobe_kobo-be-network is external, skipping
> Removing network kobobe_kobo-be-network
> WARNING: Network kobobe_kobo-be-network not found.
> Launching environment
> Creating network "kobobe_kobo-be-network" with driver "bridge"
> Creating kobobe_postgres_1    ... done
> Creating kobobe_redis_main_1  ... done
> Creating kobobe_redis_cache_1 ... done
> Creating kobobe_mongo_1       ... done
> Waiting for PostgreSQL database to be up & running...
> Creating network "kobofe_kobo-fe-network" with driver "bridge"
> The PostgreSQL database is running!
> Creating kobofe_kobocat_1        ... done
> Creating kobofe_kpi_1            ... done
> Creating kobofe_nginx_1          ... done
> Creating kobofe_enketo_express_1 ... done
> Waiting for environment to be ready. It can take a few minutes.
> ............................................................

**Desktop**

 - OS:  Ubuntu 20.04
 - Python Version: 3
 - Docker Version: 20.10.1
 - Docker Compose Version: 1.25.0
 - KoBoInstall Version: 3.2.1 (build f63357d)

**Comment by noliveleger** [comment]
It may be a problem with your proxy. Have a look to [this thread](https://community.kobotoolbox.org/t/kobo-install-http-https-certificate-nightmare/8197) in the community forum. Especially this part:
> The main important thing is to have X-Forwarded-Proto https header on the reverse proxy sent to kobo-docker frontend nginx container.

Otherwise, please open a thread on the community forum to get assistance. We use GH issues to track bugs and features. 
As the disclaimer says when you open a new issue, we cannot provided support or guidance over here.
 
> NOTE: IF YOU HAVE ANY PROBLEMS DURING THE INSTALLATION PLEASE VISIT OUR COMMUNITY FORUM AND POST YOUR DETAILED QUESTION THERE:  https://community.kobotoolbox.org/c/kobo-install. Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug in the installation script 

One more thing, you should: 
- Follow docker post-install for linux and not use `sudo` to run docker.
- Upgrade to latest version of kobo-install (but it won't fix your problem which seems to a configuration problem)

**Comment by essadek** [comment]
@noliveleger  

> Follow docker post-install for linux and not use sudo to run docker.

do you mean we can't run KoboToolbox without root user ?

**Comment by noliveleger** [comment]
@essadek, you can. But I'd rather not to avoid permission issues.
