### ISSUE TITLE
KoBoCAT form media iframe not loading over SSL

### ISSUE THREAD

**Issue by eswarsugu** [kobotoolbox/kobo-install#151]
**Description**
pulldata function Media setting is not loading over SSL.

**Steps to Reproduce**
pulldata function->Setting->Media

**Expected behavior**
pulldata function Media setting is not loading over SSL. Tested working without SSL

**Desktop**

 - OS:  Ubuntu server 18.04
 - Python Version: 3.6.9
 - Docker Version: 19.03.6, build 369ce74a3c
 - Docker Compose Version: 1.17.1
 
**Additional context**

While trying to upload a csv in media on pulldatafunction->Settings->Media. The page is not loading over SSL enabled.
Browser shows that "Mixed content: load all resources via HTTPS to improve the security of your site" 
Tested in Google Chorme and Microsoft Edge.
![Screenshot_4](https://user-images.githubusercontent.com/33921737/107611268-a628f500-6c69-11eb-9ab6-b7de204e7e54.jpg)

**Comment by mdkhamru** [comment]
![image](https://user-images.githubusercontent.com/78899591/107611910-108e6500-6c6b-11eb-849e-7dd2f2fe277f.png)
even open is not working

**Comment by jnm** [comment]
If you click on "Projects (legacy)"—it's a globe icon at the bottom, left corner of the screen, does that load for you? If so, can you find your form in the list there, click it, then click "Project Settings", and then try to upload your CSV?

Also, are you using a common domain name for both KPI and KoBoCAT? For example, this is known to work:
* KPI: kf.kobotest.org
* KoBoCAT: kc.kobotest.org

What we do **not** test is a setup like:
* KPI: kf.somedomain.org
* KoBoCAT. kc.otherdomain.org

**Comment by noliveleger** [comment]
@eswarsugu, I think there is something wrong with your configuration. 
Do you use your own proxy in front kobo-docker to provide SSL or do you use the one provided by kobo-install?

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. Please visit https://community.kobotoolbox.org/c/kobo-install for help.
