### ISSUE TITLE
![image](https://user-images.githubusercontent.com/78899591/107611910-108e6500-6c6b-11eb-849e-7dd2f2fe277f.png)

### ISSUE THREAD

**Issue by eswarsugu** [kobotoolbox/kobo-install#152]
![image](https://user-images.githubusercontent.com/78899591/107611910-108e6500-6c6b-11eb-849e-7dd2f2fe277f.png)
even open is not working

_Originally posted by @mdkhamru in https://github.com/kobotoolbox/kobo-install/issues/151#issuecomment-777256103_

**Comment by jnm** [comment]
Hi, there's a problem with your particular install—maybe Enketo is not running, or doesn't have its DNS configured properly?—but it's not an issue with kobo-install itself.

Please seek support at https://community.kobotoolbox.org/c/kobo-install/18.
