### ISSUE TITLE
Waiting for environment to be ready. It can take a few minutes.

### ISSUE THREAD

**Issue by bawantha** [kobotoolbox/kobo-install#167]
Why this take zillion years to take start ??

**Comment by bawantha** [comment]
enketo_express_1  | 17:02:10 0|enketo  | Worker 47462 sadly passed away. It will be reincarnated.
enketo_express_1  | 17:02:10 0|enketo  | Worker 3646 ready for duty at port 8005! (environment: production)
enketo_express_1  | 17:02:10 0|enketo  | Error: Redis connection to redis-cache.kobo.private:6380 failed - connect ECONNREFUSED 172.22.0.2:6380
enketo_express_1  | 17:02:10 0|enketo  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
enketo_express_1  | 17:02:10 0|enketo  |   errno: 'ECONNREFUSED',
enketo_express_1  | 17:02:10 0|enketo  |   code: 'ECONNREFUSED',
enketo_express_1  | 17:02:10 0|enketo  |   syscall: 'connect',
enketo_express_1  | 17:02:10 0|enketo  |   address: '172.22.0.2',
enketo_express_1  | 17:02:10 0|enketo  |   port: 6380
enketo_express_1  | 17:02:10 0|enketo  | }

**Comment by bawantha** [comment]
Need to add DNS record before set it up here

**Comment by mauricionuup** [comment]
Do you have any additional info on how you solved this? We had a working server for almost a year and recently stopped working. We are getting an `EPIPE` error, and if we disable reddis, we get the same ECONNREFUSED as you.  We are fairly sure that our domains are set  correctly.

**Comment by kishanio** [comment]
Same here. Doesn't finish.

**Comment by mauricionuup** [comment]
Take a look at [this conversation](https://community.kobotoolbox.org/t/kobo-install-process-failing-connection-refused/40683) from the kobotoolbox community, it solved my issue.
