### ISSUE TITLE
Hello @noliveleger

### ISSUE THREAD

**Issue by mdkhamru** [kobotoolbox/kobo-install#178]
Hello @noliveleger 

if you see above log it says kobo using celery and i not sure what consuming more and also why buffer remain ,it should clear right after some time and also note we are using only kobo on server no 3rd party apps 

![image](https://user-images.githubusercontent.com/78899591/139794887-da158544-1c00-44c8-8a01-daececd9f076.png)

![image](https://user-images.githubusercontent.com/78899591/139794974-7a9c77a0-95cc-419a-a415-c48a52137f16.png)

_Originally posted by @mdkhamru in https://github.com/kobotoolbox/kobo-install/issues/175#issuecomment-957128276_

**Comment by noliveleger** [comment]
Closed.
Please read https://github.com/kobotoolbox/kobo-install/issues/175#issuecomment-952961680
