### ISSUE TITLE
Fresh install fails with "error: pathspec 'nginx-1.21' did not match any file(s) known to git" 

### ISSUE THREAD

**Issue by zwets** [kobotoolbox/kobo-install#181]
A fresh installation of `kobo-install` fails to install KoboToolbox with _"error: pathspec 'nginx-1.21' did not match any file(s) known to git"_.

**Steps**

    git clone git@github.com:kobotoolbox:kobo-install
    cd kobo-install
    ./run.py

    # go through the installation questions (server, defaults)
    # the installer clones `../kobo-docker`, then errors:
    error: pathspec 'nginx-1.21' did not match any file(s) known to git

**Diagnosis**

The issue appears to be that `helpers/config.py` has `KOBO_DOCKER_BRANCH = 'nginx-1.21'` whereas `kobo-docker` doesn't have a branch by that name:

    $ git -C ../kobo-docker branch -a
    * master
      remotes/origin/HEAD -> origin/master
      remotes/origin/beta
      remotes/origin/hack-for-large-non-s3-exports
      remotes/origin/master
      remotes/origin/nginx-1.20
      remotes/origin/shared-database-obsolete
      remotes/origin/stop-querying-deleted-at
      remotes/origin/stop-setting-deleted-at

**Workaround / Proposed Fix**

Branch `nginx-1.21` was recently [merged on kobo-docker's master](https://github.com/kobotoolbox/kobo-docker/pull/329), so I suppose `helpers/config.py` should have `KOBO_DOCKER_BRANCH = 'master'`.

**Comment by riazarbi** [comment]
I'd like to validate that I am receiving this error as well

**Comment by noliveleger** [comment]
Hello @zwets, Thank you to bring this to our attention.
With the latest release this should be fixed.
