### ISSUE TITLE
How i can setup fresh install without domain only public IP

### ISSUE THREAD

**Issue by javquery** [kobotoolbox/kobo-install#19]
Hi folks , anyone of you know, How i can configure a new kobo server without registered domain, i just has my public ip addresss, could you please help on this

**Comment by noliveleger** [comment]
Hello @javquery,
Is there a reason why you wouldn't want to use a domain name?

**Comment by jnm** [comment]
Would you have a SSL certificate for your public IP address? This seems unusual but possible.

We probably won't add support for configuring public servers without HTTPS encryption.

**Comment by Posherman** [comment]
Hey I want to know how to reschedule my data

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. Please visit https://community.kobotoolbox.org/c/kobo-install for help.
