### ISSUE TITLE
Prompt for Mongo credentials when `server_role == 'frontend'` and `multi_servers == True`

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-install#190]
Hi @noliveleger, I noticed when changing the Mongo password on a multi-front-end-to-single-back-end installation that `run.py` did not prompt me for Mongo credentials on the front ends. I was able to edit `.run.conf` manually and then use `run.py --auto-update` successfully. Should this logic be changed, though?
https://github.com/kobotoolbox/kobo-install/blob/6f843804fd131bf5160894154def504a8d7229a0/helpers/config.py#L1335-L1341

**Comment by noliveleger** [comment]
Fixed by #191
