### ISSUE TITLE
Using previous installation when Special characters no longer accepted in database passwords 

### ISSUE THREAD

**Issue by amks1** [kobotoolbox/kobo-install#198]
## Description
I have a previous installation of Kobotoolbox on my system. The database passwords for Postgres, Mongo and Redis contain special characters. For illustration, the password is `dummypassword@123`. 

My normal method of upgrading the installation would be to clone the latest version of `kobo-install`, and point the `docker-compose` file to `build` from my local storage where I have the source code with my changes.  (I always do the fresh installation in a new folder and copy the `.vols` folder over)
I run `python3 run.py --setup` and enter the same passwords as the previous installation, so that the databases can connect. 

However in the new version (tag 2.022.24) now that only alphanumeric characters are allowed for passwords, I am not able to enter the same passwords. Entering a different password gives the following error during the setup process: 

```
CommandError: Retries exceeded; failed to connect to default database
```

 
## What I've tried:
I added `'@'` to `helpers/config.py`'s `Config` class attribute like this: 
```python3
ALLOWED_PASSWORD_CHARACTERS = (
        string.ascii_letters
        + string.digits + '@'
    )
```
While this allowed me to enter the old password, I got these errors:
```
File "/srv/src/kpi/kobo/settings/prod.py", line 2, in <module>
    from .base import *
  File "/srv/src/kpi/kobo/settings/base.py", line 867, in <module>
    mongo_client = MongoClient(
  File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 670, in __init__
    res = uri_parser.parse_uri(
  File "/opt/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 494, in parse_uri
    user, passwd = parse_userinfo(userinfo)
  File "/opt/venv/lib/python3.10/site-packages/pymongo/uri_parser.py", line 61, in parse_userinfo
    raise InvalidURI("Username and password must be escaped according to "
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus().
An error has occurred
```

## Help requested
It seems to me like the only way to proceed is to change the older database passwords. Before I go tinkering around inside the backend containers, I wanted to check with you guys to see if there's a straightforward way to update all the passwords.
If not, I'd appreciate some docs on how to change them one by one.

**Comment by noliveleger** [comment]
Closing this issue in favor of https://community.kobotoolbox.org/t/new-version-does-not-allow-special-characters-in-db-passwords/31739/4
