### ISSUE TITLE
Use "docker compose" instead of "docker-compose", or why I hate software engineering

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-install#202]
The Gods of Docker have decided it was a good use of time to rewrite docker-compose in Go as a sub-command of `docker`. Okay.

@bufke indicates that making a simple `docker-compose` alias seems to work, e.g. making `/usr/bin/docker-compose` with the content
```bash
#!/bin/bash
docker compose "$@"
```

I recall there being issues (e.g. https://github.com/docker/compose/issues/8741) with things like environment variables in the New Hotness Docker "No Dash" Compose, but if those have been ironed out, then we should do the following:
1. check for existence of `docker compose` at start of `run.py`
1. if it exists, use it for everything
1. if not, use `docker-compose`

For (1), we can check the exit code of `docker compose version`
```
# inside docker run --rm -it docker /bin/sh

/ # docker compose version
Docker Compose version v2.6.1
/ # echo $?
0
```
vs.
```
john@world:~$ docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'
john@world:~$ echo $?
1
```

**Comment by jnm** [comment]
Probably would be good to consult https://docs.docker.com/compose/cli-command-compatibility/

**Comment by javib94** [comment]
I made first the alias thing but it didn't work anyway, so I has to modify every instance of the call docker-compose, I made some other modifications so I didn't make the Pull request, but maybe someone can take it, It looks like this: 

https://github.com/desarrolloinegt/kobo-install/commit/6abcbb8d07f179b8f7fcc6dcf484838245439cac

**Comment by noliveleger** [comment]
#207 closes this issue
