### ISSUE TITLE
 Media files are not being displayed in forms

### ISSUE THREAD

**Issue by javib94** [kobotoolbox/kobo-install#204]
I have installed kobotoolbox on my own server, It works mostly correctly, a feature that we couldn't make it to work is to deploy files into the forms, so things like set an image in the form or the pulldata function is not working. I made the test in public server and on my server and the code generated in enketo in my server is missing source path. 

**Code generated in public kobotoolbox server:** 

`<img class="active" 
data-offline-src="/media/get/https/kc.kobotoolbox.org/javib94/xformsMedia/1061170/1602325.png" 
src="blob:https://ee.kobotoolbox.org/415533f5-fd79-4831-b3de-2a6366545611" 
data-itext-id="/a5kuiZcZEdYeaE7zFQKa7a/logo:label" 
alt="image" lang="default">`

**The code generated in my own server:**

`<img lang="default" 
class="active" 
data-offline-src="jr://images/LOGO.png" 
src="" 
data-itext-id="/ag8hTQHsyU9snKgP7G4PDu/logo:label" 
alt="image">`

So, I think some configuration in enketo is missing during the installation thats why I publish this here, you can correct me, if there is not any configuration missing, maybe you can guide me to fix that issue at least in my server and then help other in the community blog.

**Comment by noliveleger** [comment]
Hello @javib94, 

It's hard to give a right answer with so little info. You must have something wrong in your setup as it works as expected on our devs servers and local installs.
Having the said, you may have more change to get some help from the [community forum](https://community.kobotoolbox.org/c/kobo-install/18).
