### ISSUE TITLE
What is the latest tested version of Ubuntu for running kobo-install? [update readme.md]

### ISSUE THREAD

**Issue by notufotofuton** [kobotoolbox/kobo-install#223]
**Description**

The readme.md file states that kobo-install "... has been tested with Ubuntu 14.04, 16.04 and 18.04, CentOS 8". If kobo-install is tested/supported on more recent versions of Ubuntu, readme should be updated. Thanks!

**Comment by notufotofuton** [comment]
Anyone ? Is it safe to use the latest Ubuntu LTR? Ubuntu 18.04 is five years old.

**Comment by jnm** [comment]
It's used in production on with Ubuntu 22.04 LTS. You're right: it'd be nice to update the readme with newer versions (and remove some of the older ones).
