### ISSUE TITLE
CryptographyDeprecation warning on Ubuntu 22.04

### ISSUE THREAD

**Issue by notufotofuton** [kobotoolbox/kobo-install#224]
**Description**
When running initial setup on the latest Ubuntu LTS release (22.04), the following warning appears many times:

/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend

**Steps to Reproduce**
1. Install Ubuntu 22.04 on a fresh machine, and run `sudo apt upgrade`.
2. Create a directory (say, ~/opt) to hold kobo-install and the directories it will create.
4. `cd ~/opt`
5. `git clone https://github.com/kobotoolbox/kobo-install`
6. `cd kobo-install`.
7. `sudo python3 run.py`. Specify https, request LetsEncrypt, and use TLS on port 587.

The warnings appear after the question about activating backups.

**Expected behavior**
No deprecation warnings.

**Desktop**
 - OS:  Ubuntu 22.04.2 LTS (Jammy Jellyfish)
 - Python Version: 3.10.6
 - Docker Version: 20.10.17, build 100c70180f
 - Docker Compose Version: 1.29.2, build unknown
 
**Additional context**
The same warning occurs just running `docker.compose --version`.

**Comment by jnm** [comment]
Thanks for this important information:

> Additional context
> The same warning occurs just running docker.compose --version.

This confirms that kobo-install has no control over your issue.

You indicate you are running Python 3.10.6, but the error message clearly lists Python 3.6.

Based on `/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32`, included in your message, you are using Snap to run Docker (or Docker Compose), and the Snap contains Python 3.6 with the outdated encryption library. Please see if you can update your Snap, or switch to another method of running Docker and Docker Compose. The new `docker compose` v2 (as opposed to `docker-compose` v1) is also supported now, if that helps you: https://github.com/kobotoolbox/kobo-install/pull/207.

Again, thanks for including important detail that helped diagnose the problem. Please do, however, validate that problems are specific to the software in this repository before opening issues here.
