### ISSUE TITLE
Could not write configuration file

### ISSUE THREAD

**Issue by dntirushwa** [kobotoolbox/kobo-install#225]
**Description**
 

**Steps to Reproduce**

**Expected behavior**

**Desktop**

 - OS:  Ubuntu 22.10
 - Python Version:  3.10.7
 - Docker Version: 20.10.21, build 20.10.21-0ubuntu1~22.10.2
 - Docker Compose Version: 
 
**Additional context**

I am installing Kobotoolbox on Ubuntu 22.04 and keep facing this error " Could not write configuration file". Is anyone that could support it? What might be the issue?

**Comment by jnm** [comment]
I'm sorry to say that this is something specific with your environment. Could you check that the user account that executes `run.py` has access to create a file named `.run.conf` in the same directory as `run.py`?

If you need further assistance, please post at https://community.kobotoolbox.org/c/kobo-install/18.
