### ISSUE TITLE
Install on debian : error with postgresql

### ISSUE THREAD

**Issue by laurenthdl** [kobotoolbox/kobo-install#226]
**Description**
 
Error on postgis docker when running python3 run.py on debian

**Steps to Reproduce**

Create a debian 11 virtual machine.
download kobo-install
install git, 
Install docker and docker compose from docker repository
Install python3

`cd /home/kobo/kobo-install`

`python3 run.py`

produce 
```
CommandError: Retries exceeded; failed to connect to default database
An error has occurred

```

`docker exec -it kobobe-postgres-1 /bin/bash`
root@postgres:/# `su - postgres`
postgres@postgres:~$ `psql`
```
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?

```

when trying to launch postgresql
`service postgresql start`
returns
`No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).`

**Expected behavior**

postgresql should work.

**Desktop**

 - OS:  debian 11
 - Python Version: 3
 - Docker Version: Docker version 23.0.5, build bc4487a
 - Docker Compose Version: Docker Compose version v2.17.3
 
**Additional context**

- psql (PostgreSQL) :  14.5 (Debian 14.5-1.pgdg110+1)

**Comment by noliveleger** [comment]
As said in the disclaimer when you open a new issue

> NOTE: IF YOU HAVE ANY PROBLEMS DURING THE INSTALLATION PLEASE VISIT OUR COMMUNITY FORUM AND POST YOUR DETAILED QUESTION THERE:  https://community.kobotoolbox.org/c/kobo-install. Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug in the installation script 


please use the community forum to seek for help.
Thank you for understanding.
