### ISSUE TITLE
Error 500 when sending mail, with an private SMTP relay, on port 25, without authentication and without TLS

### ISSUE THREAD

**Issue by pilem** [kobotoolbox/kobo-install#227]
**Description**
An error 500 occurs when sending mail a local network SMTP relay, on port 25, without authentication and without TLS.

Traceback shows: « smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server ». The full traceback is shown here: https://community.kobotoolbox.org/t/server-error-500-error/10158/21

So the STARTTLS SMTP server support is validated even if SMTP_USE_TLS is set to False.

It might be a Django or a kpi error, (« use_tls » get set somewhere) but it is fixable from the configuration. See below.

**Steps to Reproduce**
Install with an SMTP server, unauthenticated, without TLS and not on localhost. With these variables:

- EMAIL_HOST=smtp-server.domain.private
- SMTP_USE_TLS=False
- EMAIL_HOST_USER=
- EMAIL_HOST_PASSWORD=

**Expected behavior**
Mail should be sent.

**Desktop**

 - OS:  CentOS 7
 - Python Version: 3.10 (conda installed)
 - Docker Version:  1.13
 - Docker Compose Version: 2.17.2
 
**Additional context**
Completely removing the SMTP_USE_TLS line from the smtp.txt config file fix this problem.

**Comment by alfawal** [comment]
This is an email server related issue.

https://stackoverflow.com/a/38138965/13438365
