### ISSUE TITLE
Unable to connect to redis-main while running kobo-install

### ISSUE THREAD

**Issue by ramaskandadigitalgreen** [kobotoolbox/kobo-install#231]
I am facing the below issue while instantiating dockers using python3 run.py (CPU utilisation is 100%). Tried the solution posted in this thread https://community.kobotoolbox.org/t/kobo-install-process-failing-connection-refused/40683/5, but did not work. Any help would be great. 

_enketo_express_1 | 13:34:21 0|enketo | Worker 4999 sadly passed away. It will be reincarnated. enketo_express_1 | 13:34:21 0|enketo | Worker 383 ready for duty at port 8005! (environment: production) enketo_express_1 | 13:34:21 0|enketo | Error: Redis connection to redis-main.odk-collect.digitalgreen.private:6379 failed - connect ECONNREFUSED [172.18.0.5:6379](http://172.18.0.5:6379/) enketo_express_1 | 13:34:21 0|enketo | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) { enketo_express_1 | 13:34:21 0|enketo | errno: ‘ECONNREFUSED’, enketo_express_1 | 13:34:21 0|enketo | code: ‘ECONNREFUSED’, enketo_express_1 | 13:34:21 0|enketo | syscall: ‘connect’, enketo_express_1 | 13:34:21 0|enketo | address: ‘172.18.0.5’, enketo_express_1 | 13:34:21 0|enketo | port: 6379 enketo_express_1 | 13:34:21 0|enketo | }_

But, i can see that redis-main and redis-cache is ready to accept connections in the respective container logs

_1:M 11 Jul 13:33:14.488 # Server started, Redis version 3.2.12
1:M 11 Jul 13:33:14.492 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add ‘vm.overcommit_memory = 1’ to /etc/sysctl.conf and $
hen reboot or run the command ‘sysctl vm.overcommit_memory=1’ for this to take effect.
1:M 11 Jul 13:33:14.492 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the $
ommand ‘echo never > /sys/kernel/mm/transparent_hugepage/enabled’ as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is
disabled.
1:M 11 Jul 13:33:14.493 * DB loaded from disk: 0.001 seconds
1:M 11 Jul 13:33:14.493 * The server is now ready to accept connections on port 6379_

**Comment by noliveleger** [comment]
As said in the disclaimer when you open a new issue

> NOTE: IF YOU HAVE ANY PROBLEMS DURING THE INSTALLATION PLEASE VISIT OUR COMMUNITY FORUM AND POST YOUR DETAILED QUESTION THERE:  https://community.kobotoolbox.org/c/kobo-install. Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug in the installation script 


please use the community forum to seek for help.
Thank you for understanding.
