### ISSUE TITLE
git error while installing 

### ISSUE THREAD

**Issue by wettanam** [kobotoolbox/kobo-install#234]
Hello
While trying to install on Uuntu server 22.04 I get this message :
Do you want to activate backups?
        1) Yes
        2) No
[2]:
Cloning into '/home/administrator/kobo-docker'...
remote: Enumerating objects: 4325, done.
remote: Counting objects: 100% (621/621), done.
remote: Compressing objects: 100% (304/304), done.
remote: Total 4325 (delta 357), reused 534 (delta 315), pack-reused 3704
Receiving objects: 100% (4325/4325), 2.47 MiB | 4.24 MiB/s, done.
Resolving deltas: 100% (2695/2695), done.
error: pathspec '2.023.37' did not match any file(s) known to git
An error has occurred

is there an issue with the repository?

Thanks

**Comment by noliveleger** [comment]
@wettanam , It should be fixed. The tag was not updated correctly.

**Comment by wettanam** [comment]
Thank you!!!
