### ISSUE TITLE
Unused environment variable(s)?

### ISSUE THREAD

**Issue by hansmbakker** [kobotoolbox/kobo-install#238]
Hi,
while setting up a kobotoolbox instance I noticed that the `REDIS_LOCK_URL` seems unused. I only see it referenced in the kobo-install script within the kobotoolbox org on github. Outside the kobotoolbox I see it referenced in [django-template](https://github.com/lorenzofabro/django-template/blob/e790aa8c8358eface3a496a68e931d5605c72d1e/core/redis_manager.py#L16) and [tg-utils](https://github.com/thorgate/tg-utils/blob/0914cc3e09ee7ad7327758aff721e35e927cb17b/tg_utils/lock.py#L16) but those seem not referenced by kobotoolbox or enketo..

Is it possible that this is something from the past, and are there more environment variables that need to be cleaned up?

https://github.com/kobotoolbox/kobo-install/blob/11727c3259e925345c53757ee2bc8a1e44ec65e8/templates/kobo-env/envfiles/databases.txt.tpl#L58

**Comment by noliveleger** [comment]
Hello @hansmbakker , 

Indeed, it has been implemented for a long time in kobo-install. 

It's for pending PRs in [kobocat](https://github.com/kobotoolbox/kobocat/pull/579) and [kpi](https://github.com/kobotoolbox/kpi/pull/2434).
