### ISSUE TITLE
SSL Not working, continual http

### ISSUE THREAD

**Issue by dai-ictgeo** [kobotoolbox/kobo-install#25]
Sorry in advance if this is a super simple issue, and to be clear this is not a bug, we are just at wits end with SSL setup and need help from those more experienced. 

We have been able to full and successfully set up kobotoolbox on a Microsoft Azure VM. We have set up the server version with frontend and backend on the same machine. All other parameters for postgres and mongo setup were left to default.  Internal and external DNS routing is working in our environment. 

My main question since documentation regarding SSL setup is thin is: Is it really as simple to setup as dropping in the crt and key files into the kobo-docker/secrets folder and restarting the nginx container? Did we miss some settings somewhere?

If this is the case, then our certs are not working properly for some reason and we can focus there (but which combo of fullchain, crt, key is required?) *we have a wildcard cert that covers our domain and all subdomains. 

We have pored over the forums and other issues, and there is no mention of changing other SSL settings in other env files. In digging through the env files I see variables related to https and public_request_headers. We have tried various combinations of those settings and certs to no avail. I would love to write up a little documentation on this when we get it running, but we need to run it first! '

Hopefully someone out there has some advice or little tidbits that can push us across the finish line, we are so close! Thanks in advance!

**Comment by noliveleger** [comment]
Hi @dai-ictgeo, 
There is a new release of kobo-install which supports SSL. 
Please have a look at this https://community.kobotoolbox.org/t/kobo-install-on-a-fresh-ubuntu-18-04-lts-vps/3250

**Comment by dai-ictgeo** [comment]
Thanks for your response!
