### ISSUE TITLE
Server mode can't install in LAN

### ISSUE THREAD

**Issue by AmirSmarty** [kobotoolbox/kobo-install#32]
Hi, everybody
I'm trying to install with server mode.But can't access in LAN.
Can you help me please?

**Comment by noliveleger** [comment]
Do you have setup your DNS to work with your LAN?
You can also search for help on https://community.kobotoolbox.org/c/kobo-install.

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. Please visit https://community.kobotoolbox.org/c/kobo-install for help.
