### ISSUE TITLE
make it possible to use existing postgresql database server

### ISSUE THREAD

**Issue by beerockxs** [kobotoolbox/kobo-install#38]
It'd be great if we could optionally use an existing postgresql database server instead of always setting up a docker container for it

**Comment by noliveleger** [comment]
@beerockxs, you can still use `kobo-install` for the first installation and then customize the configuration files (in `kobo-deployments` folder - e.g. `database.txt`) to point to your current postgresql server.

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. Please visit https://community.kobotoolbox.org/c/kobo-install for help.

**Comment by tendaitakas** [comment]
Hi. I am facing the same challenge. How do you refresh the whole deployment once you change the postgresql variables in databases.txt? The changes do not immediately take effect.

**Comment by tendaitakas** [comment]
> @beerockxs, you can still use `kobo-install` for the first installation and then customize the configuration files (in `kobo-deployments` folder - e.g. `databases.txt`) to point to your current postgresql server.

Hi. I am facing the same challenge. How do you refresh the whole deployment once you change the postgresql variables in databases.txt? The changes do not immediately take effect.
