### ISSUE TITLE
When I run $ python run.py I get ERROR: Couldn't connect to Docker daemon - you might need to run 'docker-machine start default'

### ISSUE THREAD

**Issue by dsouchon** [kobotoolbox/kobo-install#40]
Hi I am running Ubunt VM using HyperV on Windows 10 to test kobotoolbox installation
I have installed docker and docker compose and started and enabled docker
When I run $ python run.py I get
ERROR: Couldn't connect to Docker daemon - you might need to run 'docker-machine start default'

What does this mean. Is it a relevant error. What must I do next please?

**Comment by jnm** [comment]
It sounds like there's something wrong with Docker on your computer, and you won't be able to use this repository until that's resolved. Try `docker run hello-world` to verify your Docker installation.

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. Please visit https://community.kobotoolbox.org/c/kobo-install for help.
