### ISSUE TITLE
Error with "select_one_from_file" type

### ISSUE THREAD

**Issue by ekansa** [kobotoolbox/kobo-install#42]
Hi All,

I just used kobo-install, and it was a much less painful process than my deployment of Kobotoolbox last year using just the Kobo-Docker project, so THANKS!

I'm having an issue however with errors in forms that have the "select_one_from_file" type field.  When I preview my form I get a "invalid data_type: select_one_from_file wine.csv". Here's some background: 

- I followed the instructions here: https://community.kobotoolbox.org/t/extremely-long-list-of-choices/3259/2
- My form validates with https://opendatakit.org/xlsform/
- I had a similar issue last year with Kobotoolbox, but the issue is marked as resolved: https://github.com/kobotoolbox/kobo-docker/issues/183

So, does kobo-install deploy an older version of kobo-docker? If so, can I change my installation so I can get my  "select_one_from_file" field types working? Or is there another issue?

Thanks!

**Comment by jnm** [comment]
Thanks for the report. Please see https://github.com/kobotoolbox/kpi/issues/2275.
Basically, the report/export machinery (https://github.com/kobotoolbox/formpack/) has not been updated to accommodate these new question types. You can work around this somewhat by using legacy exports.
