### ISSUE TITLE
Can't build frontend from local machine with npm run watch

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kobo-install#45]
## Description

On MacOS after fresh `kobo-install` run, calling `npm run watch` command from local machine will throw error `Local package.json exists, but node_modules missing, did you mean to install?`.

Guess: this happens because `node_modules` and `jsapp/fonts` directories are symlinked.

Note that it is possible to run `npm run watch` from within the docker container, but as my short experiments showed, it will be much slower than running the same command locally.

## Temp hack fix

After fresh install, I run these commands to fix the problem:

```
rm -rf node_modules && rm -rf jsapp/fonts && npm i && npm run copy-fonts
```

## Additional details

Related flowdock threads:

- https://www.flowdock.com/app/kobotoolbox/kobo/threads/VkhUiAXSbuixlKAm1-H9emE6yHU
- https://www.flowdock.com/app/kobotoolbox/kobo/threads/tJT-6guE_Qwp7JkSn3NreoL_vLL

**Comment by noliveleger** [comment]
Closed by #61.
