### ISSUE TITLE
Nginx configure

### ISSUE THREAD

**Issue by localsnet** [kobotoolbox/kobo-install#54]
I use Plesk panel software to manage webhosting, and it include own Nginx frontend. So I need correct configure one with backend Nginx from  kobo. When I add domain  to my frontend Nginx and proxypass it to backend Nginx, in  browser I've got 

> Bad Request (400)

How correctly setup Nginx in my current environment? Please suggest me in right direction.

**Comment by noliveleger** [comment]
Hi @localsnet, 
To install with your own NginX proxy, be sure to choose advanced options when asked.
See below screenshots to setup `KoBoToolbox` with an external proxy.

Choose an external proxy with HTTPS
![Choose an external proxy with HTTPS](https://user-images.githubusercontent.com/24226825/65989029-eb72cb00-e456-11e9-8813-b4dba4f81739.png)

Choose an external proxy without HTTPS
![Choose an external proxy without HTTPS](https://user-images.githubusercontent.com/24226825/65988947-c9794880-e456-11e9-8347-7e0bc628f7fd.png)

Replace `8080` with the port your `NginX` use to communicate with backend.
With `HTTPS`, you need to pass `X-Forwarded-Proto https`. 
See this comment: https://github.com/kobotoolbox/kobo-install/issues/17#issuecomment-476203171

**Comment by localsnet** [comment]
Thank you, @noliveleger .
Actually I resolve it by this mode:
`Where do you want to install?
[/data/kobo-docker]: 
Please confirm path [/data/kobo-docker]
    1) Yes
    2) No
[1]: 
Do you want to see advanced options?
    1) Yes
    2) No
[2]: 1
What kind of installation do you need?
    1) On your workstation
    2) On a server
[2]: 
Please choose which network interface you want to use?
    enp0s31f6) n.n.n.n
    other) Other
[enp0s31f6]: 
Do you want to use separate servers for frontend and backend?
    1) Yes
    2) No
[2]: 
Public domain name [kobo.local]: example.com
KPI sub domain [kf]: 
KoBoCat sub domain [kc]: 
Enketo Express sub domain name [ee]: 
Do you want to use HTTPS?
    1) Yes
    2) No
[1]: 2
Is `KoBoToolbox` behind a reverse-proxy/load-balancer?
    1) Yes
    2) No
[1]: 
Is your reverse-proxy/load-balancer installed on this server?
    1) Yes
    2) No
[1]: 
Internal port used by reverse proxy?
[8080]: 80
Ports 80 and 443 are reserved!
[80]: 8080
SMTP server: 
SMTP port [25]: 
SMTP user: 
From email address [support@example.com]: 
Super user's username [super_admin]: 
Super user's password [#######]: 
Docker Compose prefix? (leave empty for default): 
Staging mode?
    1) Yes
    2) No
[2]: 
Postgres database [kobotoolbox]: 
Postgres user [kobo]: 
Postgres password [-######]: 
Do you want to tweak PostgreSQL settings?
    1) Yes
    2) No
[2]: 
Do you want to customize service ports?
    1) Yes
    2) No
[2]: 1
PostgreSQL?
[5432]: 
MongoDB?
[27017]: 
Redis (main)?
[6379]: 
Redis (cache)?
[6380]: 
Do you want to use AWS S3 storage?
    1) Yes
    2) No
[2]: 
Google Analytics Identifier: 
Google API Key: 
Do you want to use Sentry?
    1) Yes
    2) No
[2]: 
Do you want to tweak uWSGI settings?
    1) Yes
    2) No
[2]: 
Do you want to activate backups?
    1) Yes
    2) No
[2]: 
remote: Enumerating objects: 2990, done.`
