### ISSUE TITLE
Error nginx-certbot_default - Ubuntu 18.04

### ISSUE THREAD

**Issue by dpadron** [kobotoolbox/kobo-install#56]
Creating network "nginx-certbot_default" with the default driver
Pulling certbot (certbot/certbot:)...
Pulling nginx (nginx:1.15-alpine)...
Creating nginx-certbot_nginx_1 ... done
An error has occurred

**Comment by noliveleger** [comment]
Please refer to https://community.kobotoolbox.org/t/change-port-80-nginx/5289
