### ISSUE TITLE
Fresh install on AWS EC2 ubuntu always giving message wait for 600 seconds

### ISSUE THREAD

**Issue by dhakim** [kobotoolbox/kobo-install#59]
Hello, I am trying for almost 3 days now to install Kobo Toolbox but everytime regardless of the settings I choose, it always ending up as below:

_Waiting for environment to be ready. It can take a few minutes.
............................................................
`KoBoToolbox` has not started yet. This is can be normal with low CPU/RAM computers.

Wait for another 600 seconds?
        1) Yes
        2) No
[1]: 2

Sometimes frontend containers can not communicate with backend containers.
Restarting the frontend containers usually fixes it.

Do you want to try?
        1) Yes
        2) No
[1]: 1_

And then another wait for 600 seconds, I am not really sure what to do. running python3 run.ph --logs doesn't show much either. 

I am trying to install it on AWS EC2 ubuntu Instance having 50 GB of Hard Disk and 4 GB RAM.

Any help would be highly appreciated.

**Comment by luisbauti92** [comment]
You should try this:

Upgrade KoBoToolbox:
$kobo-install> python run.py --upgrade

**Comment by noliveleger** [comment]
@dhakim Can you share the output of `./run.py --setup`? 
Maybe some options are not correct?

**Comment by kokoye2007** [comment]
effect to me
DO 2CPU 8GB
but failed 
Wait for another 600 seconds?

**Comment by dhakim** [comment]
Thank you everyone for your contribution. Finally, Kobo Toolbox installed and is now running after like 52 installation tries / settings. 

My machine: AWS EC2 ubuntu instance, 50 GB HDD, 4 GB RAM, 1 CPU

My last remaining issue was configuring SSL choosing Lets Encrypt Certificate which was always giving issue with ngnix alpine 1.15 docker container. Below issues encountered on different settings of installations and they occur randomly. 

1. nginx alpine 1.15 docker container always restarting - never up. Remove container and installing again gives certificate error or still shows restarting status
2. certbox is not able to create another certificate if already exist from previous installation.

Having above issues, I installed kobo without SSL and it worked. Now configuring SSL on already installed Kobo gives port usage issue as nginx:latest container running on port 80 tcp which cannot be used by nginx alpine 1.15, so I tried to use some other port like 8077 which ofcourse didn't work too.

Then I configured Kobo Toolbox again without SSL, made it up, checked and working, then I update the Kobo Installation by running "python run.py -u" - then again started setup with SSL choosing Lets Encrypt Certificate and finally the magic happened and SSL got configured, really don't know how it happened but I am happy it is working now as expected.

**Comment by kokoye2007** [comment]
my status is KPI and KOBO CAT is always restart
![Screenshot from 2019-11-07 12-05-11](https://user-images.githubusercontent.com/3091754/68363011-c0ffe600-0157-11ea-9246-09a3be96ac11.png)
![Screenshot from 2019-11-07 12-03-14](https://user-images.githubusercontent.com/3091754/68363017-c1987c80-0157-11ea-91da-90ad2f89c0a2.png)

**Comment by dhakim** [comment]
Yes, not sure why but it will go try updating kobo and then setup again. first try without SSL and don't chose any port, let setup chose the default ports
