### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by khadkap** [kobotoolbox/kobo-install#60]
- OS:  Ubuntu 18.04.3 LTS
 - Python Version: Python 3.6.8
 
**Additional context**

**Traceback (most recent call last):
  File "run.py", line 55, in <module>
    run(force_setup=True)
  File "run.py", line 27, in run
    Setup.run(current_config)
  File "/home/user/kobo/kobo-install/helpers/setup.py", line 28, in run
    os.path.join(tmp_dirpath, Config.UNIQUE_ID_FILE))
OSError: [Errno 18] Invalid cross-device link: '/home/user/kobo/kobo-docker/.uniqid' -> '/tmp/tmpgwvfg6wk/.uniqid'**

**Comment by molecode** [comment]
It works for me if I replace `os.rename` with `shutil.move` in the file `helpers/setup.py`(line 28 and 38).

**Comment by noliveleger** [comment]
Fixed by @molecode's PR.
