### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by dhakim** [kobotoolbox/kobo-install#63]
Hello,

I have trying to locate that is there a way we can remove "Create an Account" link from home page/login panel and somehow create that link inside admin panel? In my case, I don't want everyone to get registered with my Kobo but I want to add the user from Admin Panel and assign them roles accordingly?

Let me know if there is a way or any workaround for this problem.

Thanks,

**Comment by noliveleger** [comment]
Hi @dhakim,
This is not an issue and not related to kobo-install.  Please use the community forum for such requests.
Having that said:
In Admin > Constance > Config > REGISTRATION_OPEN. Unchecked this option should do what you want ;-)

**Comment by dhakim** [comment]
Thanks @noliveleger  .. it worked :)
