### ISSUE TITLE
Firewall can block frontend containers from connecting to backend containers

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kobo-install#77]
@duvld said: 

make sure if running on Linux to either disable firewall or make a rule to allow kpi, if firewall blocks kpi from connecting to backend strange errors will come up.

Maybe we should write something about this in a readme or in the `run.py -s` prompts.

_Originally posted by @duvld in https://github.com/kobotoolbox/kobo-install/pull/76#issuecomment-602635151_

**Comment by jnm** [comment]
If #72 and kobotoolbox/kobo-docker#266 solve the firewall issue for single-machine installs (by not depending on open ports), that would be great. Then we could avoid asking the installer to do more (potentially confusing) work

Originally posted in https://github.com/kobotoolbox/kobo-install/pull/76#issuecomment-602853755

**Comment by noliveleger** [comment]
@jnm, when the firewall is active and ports are not exposed. Docker uses its internal network to communicate between containers. 

> If #72 and [kobotoolbox/kobo-docker#266](https://github.com/kobotoolbox/kobo-docker/pull/266) solve the firewall issue for single-machine installs (by not depending on open ports), that would be great. Then we could avoid asking the installer to do more (potentially confusing) work
> 
> Originally posted in [#76 (comment)](https://github.com/kobotoolbox/kobo-install/pull/76#issuecomment-602853755)

@jnm, Indeed. when the firewall is active and ports are not exposed, it works (docker uses its internal network to communicate between containers).

**Comment by almereyda** [comment]
It would be good to add a note to the README or to the installer script that one ought to review one's firewall configuration before attempting the deployment.

**Comment by noliveleger** [comment]
@almereyda, it is on the PR of #72.
It's not an issue anymore with backend ports not exposed (which is a new option of #72). 
The only port which needs to be open is the NGINX's one. As you suggested, I've updated the README in this PR to make it clearer (I hope :-) )
