### ISSUE TITLE
Problems with geopoint widgtes on enketo forms

### ISSUE THREAD

**Issue by jonathanf** [kobotoolbox/kobo-install#82]
**Description**
 
There is a problem with location widgets all of them (in humanitarianresponse.info or in self hosted are unfocused:

**Steps to Reproduce**

Create geopoint field with default location or search a location and You can see the point in the top left corner instead in the vertical and horizontal center. 

![Captura de pantalla de 2020-04-14 17-57-23](https://user-images.githubusercontent.com/926635/79282313-7e66d600-7e7a-11ea-85ac-824adca74d41.png)

And never navigate as spect if you go to the right.

**Expected behavior**

The point must be in the vertical and horizontal center, and the navigation must be as always.

**Desktop**

 - OS:  Ubuntu 18.04.4 LTS
 - Python Version: 3.6.9
 - Docker Version: Docker version 19.03.8, build afacb8b7f0
 - Docker Compose Version: docker-compose version 1.24.1, build 4667896b
 
**Additional context**

**Comment by noliveleger** [comment]
Hey @jonathanf,

It seems related to `enketo_express`. Please close this issue and open it [there].(https://github.com/enketo/enketo-express)
