### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by Stopi** [kobotoolbox/kobo-install#9]
Hi, I just tried to install this and it's not working.
Here is my config :
- Alpine Linux 3.8.2 (last version, up to date) running on HyperV
- docker 18.09.1-r0
- docker-compose 1.23.2

Here the output :
```
kobo [/home/kobo-install]# python run.py
╔═══════════════════════════════════════════════════════════════╗
║ Welcome to `kobo-install`!                                    ║
║                                                               ║
║ You are going to be asked some questions that will            ║
║ determine how to build the configuration of `KoBoToolBox`.    ║
║                                                               ║
║ Some questions already have default values (within brackets). ║
║ Just press `enter` to accept the default value or enter `-`   ║
║ to remove previously entered value.                           ║
║ Otherwise choose between choices or type your answer.         ║
╚═══════════════════════════════════════════════════════════════╝
Where do you want to install?
[/home/kobo-docker]:
Do you want to see advanced options?
        1) Yes
        2) No
[2]:
What kind of installation do you need?
        1) On your workstation
        2) On a server
[2]:
Public domain name [kobo.local]: mydomain.tld
KPI sub domain [kf]: koboform
KoBoCat sub domain [kc]: kobocat
Enketo Express sub domain name [ee]: enketo
Do you use a reverse proxy or a load balancer?
        1) Yes
        2) No
[1]:
Use HTTPS?
Please note that certificate has to be installed on the load balancer!
        1) Yes
        2) No
[1]:
Internal port used by reverse proxy?
[80]:
SMTP server: mail.mydomain.tld
SMTP port [25]: 587
SMTP user: robot@mydomain.tld
SMTP password: xxxx
Use TLS?
        1) True
        2) False
[1]:
From email address [support@mydomain.tld]: robot@mydomain.tld
Super user's username [super_admin]:
Super user's password [^H$kNO-Tdi1Aq%EB]: xxxx
Do you want to activate backups?
        1) Yes
        2) No
[2]:
Cloning into '/home/kobo-docker'...
remote: Enumerating objects: 2546, done.
remote: Total 2546 (delta 0), reused 0 (delta 0), pack-reused 2546
Receiving objects: 100% (2546/2546), 1.84 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (1580/1580), done.
Switched to a new branch 'kobo-install'
From https://github.com/kobotoolbox/kobo-docker
 * branch            kobo-install -> FETCH_HEAD
Removing network kobo-docker_default
WARNING: Network kobo-docker_default not found.
Removing network kobo-docker_kobo-fe-network
WARNING: Network kobo-docker_kobo-fe-network not found.
Launching environment
Creating network "kobo-docker_default" with the default driver
Pulling mongo (mongo:3.4)...
Pulling redis_main (redis:3.2)...
Pulling postgres (mdillon/postgis:9.5)...
Pulling rabbit (kobotoolbox/rabbit:latest)...
Creating kobo-docker_mongo_1       ... done
Creating kobo-docker_postgres_1    ... done
Creating kobo-docker_rabbit_1      ... done
Creating kobo-docker_redis_main_1  ... done
Creating kobo-docker_redis_cache_1 ... done
Creating network "kobo-docker_kobo-fe-network" with driver "bridge"
WARNING: Found orphan containers (kobo-docker_redis_cache_1, kobo-docker_rabbit_1, kobo-docker_redis_main_1, kobo-docker_postgres_1, kobo-docker_mongo_1) for this project. If you removed or renamed this service in your compose file, you
can run this command with the --remove-orphans flag to clean it up.
Pulling nginx (kobotoolbox/nginx:latest)...
Pulling kobocat (kobotoolbox/kobocat:2.018.48)...
Pulling enketo_express (kobotoolbox/enketo-express-extra-widgets:1.72.2)...
Pulling kpi (kobotoolbox/kpi:2.018.48)...
Creating kobo-docker_enketo_express_1 ... done
Creating kobo-docker_kpi_1            ... done
Creating kobo-docker_nginx_1          ... done
Creating kobo-docker_kobocat_1        ... done
Waiting for environment to be ready. It can take a few minutes.
............................................................
`KoBoToolbox` has not started yet, wait for another 600 minutes!
............................................................
`KoBoToolbox` has not started yet, sometimes frontend containers can not communicate with backend containers.
Let's restart frontend containers.

Stopping kobo-docker_nginx_1          ... done
Stopping kobo-docker_kpi_1            ... done
Stopping kobo-docker_kobocat_1        ... done
Stopping kobo-docker_enketo_express_1 ... done
WARNING: Found orphan containers (kobo-docker_redis_cache_1, kobo-docker_rabbit_1, kobo-docker_redis_main_1, kobo-docker_postgres_1, kobo-docker_mongo_1) for this project. If you removed or renamed this service in your compose file, you
can run this command with the --remove-orphans flag to clean it up.
Removing kobo-docker_nginx_1          ... done
Removing kobo-docker_kpi_1            ... done
Removing kobo-docker_kobocat_1        ... done
Removing kobo-docker_enketo_express_1 ... done
Removing network kobo-docker_kobo-fe-network
Launching frontend containers
Creating network "kobo-docker_kobo-fe-network" with driver "bridge"
WARNING: Found orphan containers (kobo-docker_redis_cache_1, kobo-docker_rabbit_1, kobo-docker_redis_main_1, kobo-docker_postgres_1, kobo-docker_mongo_1) for this project. If you removed or renamed this service in your compose file, you
can run this command with the --remove-orphans flag to clean it up.
Creating kobo-docker_enketo_express_1 ... done
Creating kobo-docker_kpi_1            ... done
Creating kobo-docker_nginx_1          ... done
Creating kobo-docker_kobocat_1        ... done
...........................................................
Something went wrong! Please look at docker logs
```
The docker logs can be accessed here : http://dl.pasteur.la/?t=8755da5a95e39d223a3109829c5ad5cd
The syslog output `/var/log/docker.log` is here : http://dl.pasteur.la/?t=f4e53dd70f9c1cf9e7f51b12ab89054f
Any help would be appreciated, thanks.

**Comment by Stopi** [comment]
By the way, when it says
```
`KoBoToolbox` has not started yet, wait for another 600 minutes!
```
I think it rather about 600 **seconds**.

**Comment by jnm** [comment]
@Stopi, this is a great opportunity to open a PR :wink: 
> I think it's rather about 600 seconds.

**Comment by Stopi** [comment]
Done : https://github.com/kobotoolbox/kobo-install/pull/11

**Comment by noliveleger** [comment]
I've tested with:
- Alpine 3.9
- docker 18.09.1-r0
- docker-compose 1.23.2

And it worked flawlessly. 
So I think it's a configuration issue.
Because you chose the `server` mode, all domain names must be reachable through the DNS (e.g. ` kobocat.mydomain.tld`, `koboform.mydomain.tld`, `enketo.mydomain.tld`) . Otherwise it won't work. 
You also said, you have an `Apache` as proxy in front of the `kobotoolbox` containers. Does Apache listen to port `80` as well as `443`?  If the answer is yes and Apache is on the same machine as `kobo-install`, you have to change the port to something else when prompt 
```
Internal port used by reverse proxy?
[80]:
``` 
Otherwise there will be a conflict between `Apache` ports and `Kobo NginX` ports.

**Comment by Stopi** [comment]
Unfortunately this will not help me.
The DNS are good, I've checked this from inside and outside the VM.
Apache is on another machine, redirecting to this VM, I've checked this also, it works.
I need to use this Apache proxy because I want the Kobo server to be accessed from Internet.

I'm going to restart a new VM with Alpine 3.9, since it's out and you succeed with it.
I'll post here my feedback.

**Comment by noliveleger** [comment]
Because you set up everything correctly. 
Maybe it's a bug with the command that tries to detect it `kobotoolbox` is up&running. 
You can try that within your VM.
Add to `/etc/hosts/`
   `X.X.X.X    koboform.docker.internal koboform.mydomain.internal` (where `X.X.X.X` is the local ip of the VM and `mydomain` is your real domain name)
When it's done. 
Try these:
- `curl -I http://koboform.docker.internal/service_health/` 
- `curl -I http://koboform.mydomain.internal/service_health/` 

What do you get?

**Comment by Stopi** [comment]
First I have to launch the process, if not then nothing listen at port 80.
```
python run.py
Creating kobo-docker_enketo_express_1 ... done
Creating kobo-docker_kpi_1            ... done
Creating kobo-docker_nginx_1          ... done
Creating kobo-docker_kobocat_1        ... done
Waiting for environment to be ready. It can take a few minutes.
..............
```
While in this step (which take a while), I've got answers :
```
kobo [~]# curl -I http://koboform.docker.internal/service_health/
HTTP/1.1 204 No Content
Server: nginx/1.10.3 (Ubuntu)
Date: Tue, 05 Feb 2019 02:51:23 GMT
Connection: keep-alive

kobo [~]# curl -I http://koboform.mydomain.internal/service_health/
HTTP/1.1 502 Bad Gateway
Server: nginx/1.10.3 (Ubuntu)
Date: Tue, 05 Feb 2019 02:51:39 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 182
Connection: keep-alive
```
Then if I wait a bit
```
kobo [~]# curl -I http://koboform.mydomain.internal/service_health/
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx/1.10.3 (Ubuntu)
Date: Tue, 05 Feb 2019 02:52:36 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
Content-Language: en
```
And waiting more finally gives me
```
kobo [~]# curl -I http://koboform.mydomain.internal/service_health/
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Tue, 05 Feb 2019 02:56:04 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
Content-Language: en
```
But after some times it fails anyway :
```
............................................................
`KoBoToolbox` has not started yet, sometimes frontend containers can not communicate with backend containers.
Let's restart frontend containers.
```
And then it restart the cycle one more time.

**Comment by Stopi** [comment]
That did the trick !
I just had to add these lines in Apache Vhost configuration file :
```
RequestHeader set X-Forwarded-Proto https
```
Now everything is working perfectly, from Internet and/or internal network to the VM.

Thank you very much for your help.

**Comment by Stopi** [comment]
If it can help someone, I put here the working Apache 2.4 vhost config :
```
<VirtualHost *:80>
    ServerName koboform.mydomain.tld
    Redirect permanent / https://koboform.mydomain.tld/
</VirtualHost>

<VirtualHost *:443>
    ServerName koboform.mydomain.tld

    ErrorLog /var/log/apache2/kobotoolbox-error
    CustomLog /var/log/apache2/kobotoolbox-access combined

    SSLEngine on
    SSLCertificateFile    /full/path/to/kobo-fullchain.crt
    SSLCertificateKeyFile /full/path/to/kobo.key
    RequestHeader set X-Forwarded-Proto https

    TimeOut 600
    ProxyPass / http://kobovm_IP:80/
    ProxyPassReverse / http://kobovm_IP:80/
    ProxyPreserveHost on

    <ifModule mod_headers.c>
        Header unset ETag
        Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
        Header set Pragma "no-cache"
        Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
    </ifModule>
</VirtualHost>
```

**Comment by coulibaly080635** [comment]
Hi,
have same problems.
My internal link works fine.
root@kobo:/home/kobo/kobo-install# curl -I http://koboml.xxxxxxi.internal:8080/service_health/
HTTP/1.1 200 OK
Server: nginx/1.19.6
Date: Fri, 05 Feb 2021 14:36:21 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 329
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Vary: Accept-Language, Cookie, Origin
Content-Language: en

I use apache in 80 and 443. 
KOBO NGIN  in 8080.

this is my apache configuration:
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin webmaster@localhost
                DocumentRoot /var/www/html
                ServerName koboml.xxxxxxx.com


                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                SSLEngine on

                SSLCertificateFile      /etc/apache2/ssl/ca.pem
                SSLCertificateKeyFile /etc/apache2/ssl/ca.key


                SSLCertificateChainFile /etc/apache2/ssl/intermediaire.cer

                RequestHeader set X-Forwarded-Proto https


                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>

                ProxyPass / http://1xxxxxx:8080
                ProxyPassReverse /  http://xxxxxx:8080

                 <ifModule mod_headers.c>
                        Header unset ETag
                        Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
                        Header set Pragma "no-cache"
                </ifModule>
        </VirtualHost>
</IfModule>

**Comment by coulibaly080635** [comment]
Come you help me. please.

**Comment by bawa-ra** [comment]
Anyone has nginx conf???

**Comment by zwets** [comment]
> If it can help someone, I put here the working Apache 2.4 vhost config :
> ```
>     ProxyPreserveHost on
> ```

This is what did the trick here!
