### ISSUE TITLE
Require certain versions of Python 3?

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-install#93]
I know we still support Python 2.7 and only warn people to upgrade at this point, but maybe we should check for Python 3.6+ (or more recent?). I noticed that someone on the forum is using Python 3.5, which, for example, doesn't support f strings. It's not (yet) enough to say that we require supported versions of Python, since 3.5 is getting security updates until 2020-09-13: https://en.wikipedia.org/wiki/History_of_Python

**Comment by noliveleger** [comment]
In the README, it says `Python3.5+` but we can drop support for Python2 and Python <= 3.5 within one of the next releases. 
It would be nice to start using f-strings instead of `.format()`

**Comment by jnm** [comment]
The README seems like enough for now, thanks. I don't think we need this issue to track ending support for Python 2.
